version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "8080:80"  # Ánh xạ cổng 8080 (host) với cổng 80 (container)
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped